# Default values for elasticsearch_backup_restore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: connections

image:
  repository: artifactory.swg.usma.ibm.com:6562
  tag: latest
  pullPolicy: IfNotPresent

elasticSearchRestore: false
elasticSearchBackup: false

REPONAME: "connectionsmetrics"
