apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: 905409959051.dkr.ecr.us-east-1.amazonaws.com/connections-docker/redis
        imagePullPolicy: Always
        command: 
        - bash
        - "-c"
        - |
          set -ex           
          [[ `hostname` =~ -([0-9]+)$ ]]
          echo hostname
          ordinal=${BASH_REMATCH[1]}         
                    
          echo ordinal
          if [[ $ordinal -eq 0 ]]; then
                echo "I'm the master"
                if [[ ! -e /redis-master-data ]]; then
                    echo "Redis master data doesn't exist, data won't be persistent!"
                    mkdir /redis-master-data
                fi
                redis-server /redis-master/redis.conf --protected-mode no
                
          else
                echo "I'm a slave"
                while true; do
                    counter=0
                    while [ $counter -lt 5 ]; do
                        master=$(redis-cli -h redis-sentinel -p 26379 --csv SENTINEL get-master-addr-by-name mymaster | tr ',' ' ' | cut -d' ' -f1)
                        if [[ -n ${master} ]]; then
                          master="${master//\"}"
                          break
                        else
                          echo "Failed to find master.  Waiting for redis-sentinel."
                          sleep 60
                          let counter=counter+1
                        fi
                    done
                    redis-cli -h ${master} INFO
                    if [[ "$?" == "0" ]]; then
                      break
                    fi
                    echo "Connecting to master failed.  Waiting..."
                    sleep 10
                  done
                  sed -i "s/%master-ip%/${master}/" /redis-slave/redis.conf
                  sed -i "s/%master-port%/6379/" /redis-slave/redis.conf
                  redis-server /redis-slave/redis.conf --protected-mode no
          fi
          
          exec "$@"          
        ports:
        - containerPort: 6379
          name: redis
        
