###################################################################
# IBM Confidential
#
# OCO Source Materials
#
# Copyright IBM Corp. 2016, 2017
#
# The source code for this program is not published or otherwise
# divested of its trade secrets, irrespective of what has been
# deposited with the U.S. Copyright Office.
###################################################################
apiVersion: v1
kind: Service
metadata:
  name: zookeeper1
  labels:
    app: zookeeper-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper2
  labels:
    app: zookeeper-2
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-2
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper3
  labels:
    app: zookeeper-3
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: solr1
    role: service
    hostname: solr1
  name: solr1
spec:
  ports:
    - name: solr1
      protocol: TCP
      port: 8983
      targetPort: 8983
  selector:
    name: "solr1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: solr2
    role: service
    hostname: solr2
  name: solr2
spec:
  ports:
    - name: solr2
      protocol: TCP
      port: 8983
      targetPort: 8983
  selector:
    name: "solr2"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: solr3
    role: service
    hostname: solr3
  name: solr3
spec:
  ports:
    - name: solr3
      protocol: TCP
      port: 8983
      targetPort: 8983
  selector:
    name: "solr3"

