###################################################################
# IBM Confidential
#
# OCO Source Materials
#
# Copyright IBM Corp. 2016, 2017
#
# The source code for this program is not published or otherwise
# divested of its trade secrets, irrespective of what has been
# deposited with the U.S. Copyright Office.
###################################################################
apiVersion: v1
kind: Service
metadata:
  labels:
    name: retrievalservice
    role: service
    hostname: retrievalservice
  name: retrievalservice
spec:
  ports:
    - name: retrievalservice
      protocol: TCP
      port: 9102
      targetPort: 9102
  selector:
    name: "retrievalservice"

