apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-index-backup-claim-for-upgrade
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
