###################################################################
# IBM Confidential
#
# OCO Source Materials
#
# Copyright IBM Corp. 2016, 2017
#
# The source code for this program is not published or otherwise
# divested of its trade secrets, irrespective of what has been
# deposited with the U.S. Copyright Office.
###################################################################
apiVersion: v1
kind: Service
metadata:
  labels:
    name: indexingservice
    role: service
    hostname: indexingservice
  name: indexingservice
spec:
  ports:
    - name: indexingservice
      protocol: TCP
      port: 9101
      targetPort: 9101
  selector:
    name: "indexingservice"

