apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: ${environment['environment']}
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: myregkey
      containers:
        - name: mongo
#          image: artifactory.swg.usma.ibm.com:6556/middleware/mongodb
          image: 905409959051.dkr.ecr.us-east-1.amazonaws.com/connections-docker/mongodb
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
#          image: artifactory.swg.usma.ibm.com:6556/middleware/mongodb-rs-setup
          image: 905409959051.dkr.ecr.us-east-1.amazonaws.com/connections-docker/mongodb-rs-setup
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=${environment['environment']}"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
