apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel
spec:
  serviceName: redis-sentinel
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis-sentinel
        image: 905409959051.dkr.ecr.us-east-1.amazonaws.com/connections-docker/redis
        imagePullPolicy: Always
        command: 
        - bash
        - "-c"
        - |
          set -ex           
          [[ `hostname` =~ -([0-9]+)$ ]]
          echo hostname          
          
          sentinel_conf=sentinel.conf
          
          echo "sentinel monitor mymaster $(eval getent hosts redis-0.redis.default.svc.cluster.local | awk '{ print $1 ; exit }') 6379 2" > ${sentinel_conf}
          echo "sentinel down-after-milliseconds mymaster 60000" >> ${sentinel_conf}
          echo "sentinel failover-timeout mymaster 180000" >> ${sentinel_conf}
          echo "sentinel parallel-syncs mymaster 1" >> ${sentinel_conf}
          echo "bind 0.0.0.0"

          redis-sentinel ${sentinel_conf} --protected-mode no
          
          exec "$@"                 
        ports:
        - containerPort: 26379
          name: redis-sentinel
